### ISSUE TITLE
Set-ArduinoPort doesn't seem to be working

### ISSUE THREAD

**Issue by wikijm** [toenuff/WinArduino#3]
Hi @toenuff,

Is it possible to get some help?
Set-ArduinoPort doesn't seem to be working on my computer.

Here is a screencast of the issue:
![set-arduinoport_issue](https://user-images.githubusercontent.com/10724809/45589895-2aa6aa80-b92e-11e8-9770-734d99379c7e.gif)

For the context, I try to work with a Digispark Rev3 ATtiny85.

Sincerely,
@wikijm

**Comment by toenuff** [comment]
Years later, but you are correct.  Fixing now.
